version: '3.8'

services:
  # 1. Database
  db:
    image: postgres:15-alpine
    container_name: app_db
    restart: always
    environment:
      POSTGRES_USER: devops_user
      POSTGRES_PASSWORD: devops_password
      POSTGRES_DB: app_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  # 2. Backend API
  backend:
    build: ./backend
    container_name: app_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: devops_user
      DB_PASSWORD: devops_password
      DB_NAME: app_db
      PORT: 5000
    depends_on:
      - db
    networks:
      - app-network

  # 3. Frontend User
  frontend-user:
    build: ./frontend-user
    container_name: app_user
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  # 4. Frontend Admin
  frontend-admin:
    build: ./frontend-admin
    container_name: app_admin
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - app-network

  # 5. Reverse Proxy (Nginx)
  nginx:
    image: nginx:alpine
    container_name: app_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend-user
      - frontend-admin
    networks:
      - app-network

  # --- DEVOPS MONITORING STACK ---

  # 6. Prometheus (Metrics Collector)
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: devops_prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - app-network

  # 7. Grafana (DevOps Dashboard)
  grafana:
    image: grafana/grafana:10.0.0
    container_name: devops_grafana
    restart: always
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=adminops
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  grafana_data: